#!/bin/bash

export DESKTOP_CORE_NAME="xquartz"
export DESKTOP_CORE_BIN_NAME="$DESKTOP_CORE_NAME"
export DESKTOP_CORE_VERSION=v2.8.5
export DESKTOP_CORE_ORG="XQuartz"

export DESKTOP_CORE_RELEASE_DOWNLOAD="https://github.com/${DESKTOP_CORE_ORG}/XQuartz/releases/download"
